paths:
  train_csv: "data/train_labels.csv"
  test_csv: "data/test_labels.csv"
  train_frames: "data/train_frames"
  test_frames: "data/test_frames"
  model_save_path: "models/optimized_model.pth"

training:
  batch_size: 16
  epochs: 10
  learning_rate: 0.001

model:
  pretrained: true
  num_classes: 2
  dropout: 0.3
